# copy pasted from https://docs.gitlab.com/ee/ci/yaml/workflow.html#skip-pipelines-for-draft-merge-requests
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE =~ /^(\[Draft\]|\(Draft\)|Draft:)/
      when: never

stages:
  - build

build-job:
  stage: build
  script:
    - irm https://deno.land/x/gitlab_ci/setup.ps1 | iex
    - deno run --allow-net --allow-read --allow-env --allow-write --allow-run ./main.ts