name: Update bundle

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
        - bundle.js

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - uses: denoland/setup-deno@v2
        with:
            deno-version: canary
      - name: Set up git user
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
      - run: deno task run
      - run: git push